#!/usr/bin/env bash
# Configure your domain zone so that the 
#subdomain www points to your load-balancer IP (lb-01).
#Let’s also add other subdomains to make our life easier, 
#and write a Bash script that will display information about subdomains
printsplited()
{
    awk '{split($1,arg,"."); print "The subdomain", arg[1], "is a", $4, "record and points to", $5}'
}

if [ $# -eq 1 ]; then
    dig "www.$1" | grep -A1 "ANSWER SECTION:" | grep -v  "ANSWER SECTION:" | printsplited
    dig "lb-01.$1" | grep -A1 "ANSWER SECTION:" | grep -v  "ANSWER SECTION:" | printsplited
    dig "web-01.$1" | grep -A1 "ANSWER SECTION:" | grep -v  "ANSWER SECTION:" | printsplited
    dig "web-02.$1" | grep -A1 "ANSWER SECTION:" | grep -v  "ANSWER SECTION:" | printsplited
else
    dig "$2.$1" | grep -A1 "ANSWER SECTION:" | grep -v  "ANSWER SECTION:" | printsplited
fi
