#!/usr/bin/env bash
#bash script install nginx and put on it hello world
sudo apt update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
