#!/usr/bin/env bash
# Script That add header x server to ngiunx config
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "17i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
