#!/usr/bin/env bash
#bash script that Configure HAproxy so that it send traffic to web-01 and web-02
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "frontend haproxy-main
	bind *:80
        option forwardfor  
	default_backend apache_webservers    

backend apache_webservers
	balance roundrobin
	server web-01   35.237.188.192:80 check
	server web-02	34.139.154.71:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
